### PR TITLE
[LOOP-1125] Upload pump data

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1125
- https://tidepool.atlassian.net/browse/LOOP-1124
- https://tidepool.atlassian.net/browse/LOOP-3389
- https://tidepool.atlassian.net/browse/LOOP-3388
- Upload pump data
- Translate SyncPumpEvent to appropriate backend data types
- Combine dose and pump event data for upload
- Update IdentifiableDatum to eliminate namespace issue
- Update tests

### CODE REVIEW

**Comment by darinkrauss** [comment]
LW PR for build: https://github.com/tidepool-org/LoopWorkspace/pull/741

**Review by rickpasetto — APPROVED** [review]
LGTM

**Comment by darinkrauss** [comment]
@ps2 @rickpasetto Ready for another review.

**Review by rickpasetto — APPROVED** [review]
LGTM

**Comment by darinkrauss** [comment]
@ps2 @rickpasetto Ready for another review. Hopefully this is the last one.

**Review by rickpasetto — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
