### PR TITLE
LOOP-340 Integrate latest TidepoolKit into TidepoolService

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-340
- Add empty implementation of RemoteDataService
- Update Cartfile to latest LoopKit and TidepoolKit

### CODE REVIEW

**Review by rickpasetto — CHANGES_REQUESTED** [review]
`Carthage/Build` files shouldn't be checked in, IMO.  Folks should run `carthage bootstrap` on their own, and the whole `Carthage` subdirectory should be added to `.gitignore`.

**Comment by darinkrauss** [comment]
@rickpasetto You brought up this same concern in an earlier PR. Please see https://github.com/tidepool-org/TidepoolService/pull/3 for our conversation. If you feel strongly that we should not be doing this for both `TidepoolService` and `DashKit`, please feel free to bring it up with the team so at least @ps2 can comment.

**Comment by rickpasetto** [comment]
@darinkrauss ok.  Can you wait until that discussion, or do you need to get this in sooner?

**Comment by darinkrauss** [comment]
@rickpasetto Removed cached Carthage build.

**Review by rickpasetto — APPROVED** [review]
LGTM

**Review by nhamming — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]

**Pull request merged**
