### PR TITLE
targetting iOS 13.0 for swiftui

### PR DESCRIPTION
**Pull request by nhamming**

### CODE REVIEW

**Review by darinkrauss — CHANGES_REQUESTED** [review]
Please push the target-specific changes up to the project level.

**Comment by nhamming** [comment]
> Please push the target-specific changes up to the project level.

Sure. I only updated the necessary targets, but I can update for the project instead.

**Review by darinkrauss — CHANGES_REQUESTED** [review]
Sorry, not to be pedantic, but I meant change the project settings (as you did) and *remove* the per-target settings (so just the project settings takes effect).

**Comment by darinkrauss** [comment]
The project was setup so that all of the common settings were at the project level and only the few per-target specific changes were specified in the target settings.

**Comment by nhamming** [comment]
> Sorry, not to be pedantic, but I meant change the project settings (as you did) and _remove_ the per-target settings (so just the project settings takes effect).

No my bad. I should have reverted the target specific updates. Doing that now.

**Review by darinkrauss — APPROVED** [review]
Thanks! LGTM! 🚀

**Pull request merged**
